name: DoerApp
options:
  bundleIdPrefix: com.doer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    exactVersion: "2.5.1"

targets:
  DoerApp:
    type: application
    platform: iOS
    sources:
      - path: DoerApp
    entitlements:
      path: DoerApp/DoerApp.entitlements
    settings:
      base:
        INFOPLIST_FILE: DoerApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.doer.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
    dependencies:
      - package: Supabase
